name: Sync multiple branches
  
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 23 13 02 *'

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: gaming
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: gaming-wait
          target_branch: gh-pages
          github_token: ${{ github.token }}
